const Constructor = (()=>{
function n(x,label,min=0,max=1){if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>max)throw Error(label+' 超出范围');return x}
function construct(r,prices='',o={}){const rows=Object.fromEntries(r.screen.rows.map(x=>[x.symbol,x])),ids=o.selected??r.screen.selected.slice(0,5),method=o.method||'equal',cash=n(o.cash_floor??.1,'现金底线'),cap=n(o.asset_cap??.3,'单票上限',.001,1),scap=n(o.sector_cap??.5,'行业上限',.001,1),capital=n(o.capital??100000,'资金',1,1e12),fee=n(o.fee_bps??10,'成本bp',0,500);
if(new Set(ids).size!==ids.length||ids.some(i=>!rows[i]?.passed))throw Error('只能选择通过筛选的不同标的');if(!['equal','score_weighted','vol_inverse','manual'].includes(method))throw Error('未知配置规则');let w=Object.fromEntries(ids.map(i=>[i,0])),budget=1-cash;
if(method==='manual'){if(Object.keys(o.manual||{}).some(i=>!ids.includes(i)))throw Error('手动权重含未选标的');ids.forEach(i=>w[i]=n(o.manual?.[i]??0,'权重'));const ss={};for(const i of ids){if(w[i]>cap+1e-10)throw Error('手动权重超过单票上限');ss[rows[i].sector]=(ss[rows[i].sector]||0)+w[i]}if(Object.values(w).reduce((a,b)=>a+b,0)>budget+1e-10||Object.values(ss).some(v=>v>scap+1e-10))throw Error('手动配置违反现金或行业约束')}
else{let raw=Object.fromEntries(ids.map(i=>[i,method==='equal'?1:method==='score_weighted'?Math.max(0,rows[i].score.score||0):(rows[i].market.volatility_20d>0?1/rows[i].market.volatility_20d:0)]));for(let iter=0;iter<ids.length*3+3;iter++){const ss={};ids.forEach(i=>ss[rows[i].sector]=(ss[rows[i].sector]||0)+w[i]);let rem=budget-Object.values(w).reduce((a,b)=>a+b,0),free=ids.filter(i=>raw[i]>0&&w[i]<cap-1e-12&&ss[rows[i].sector]<scap-1e-12);if(rem<=1e-12||!free.length)break;let total=free.reduce((a,i)=>a+raw[i],0),delta=Object.fromEntries(free.map(i=>[i,rem*raw[i]/total])),scale=1;free.forEach(i=>scale=Math.min(scale,(cap-w[i])/delta[i]));for(const s of new Set(free.map(i=>rows[i].sector))){let proposed=free.filter(i=>rows[i].sector===s).reduce((a,i)=>a+delta[i],0);scale=Math.min(scale,(scap-(ss[s]||0))/proposed)}free.forEach(i=>w[i]+=Math.max(0,scale)*delta[i])}}
const current=o.current||{};Object.keys(current).forEach(i=>{if(!rows[i])throw Error('现持仓不在当前数据中');n(current[i],'当前权重')});if(Object.values(current).reduce((a,b)=>a+b,0)>1+1e-10)throw Error('当前持仓超过100%');const holdings=ids.map(i=>({entity_id:i,sector:rows[i].sector,weight:w[i],price:rows[i].price,amount:capital*w[i],reference_shares:capital*w[i]/rows[i].price,evidence_ids:rows[i].evidence_ids})),total=Object.values(w).reduce((a,b)=>a+b,0),cashw=Math.max(0,1-total),hist={};
if(prices.trim())Investment.csv(prices,Investment.PF,'prices',80000).forEach(x=>{if(x.date<=r.as_of&&ids.includes(x.symbol))(hist[x.symbol]??=[]).push({date:x.date,close:+x.adj_close})});for(const i of Object.keys(hist)){hist[i].sort((a,b)=>a.date.localeCompare(b.date));if((Date.parse(r.as_of)-Date.parse(hist[i].at(-1).date))/86400000>7)delete hist[i]}
const risk=Investment.stress({holdings},hist),trades=[...new Set([...ids,...Object.keys(current)])].sort().map(i=>({symbol:i,current:current[i]||0,target:w[i]||0,delta:(w[i]||0)-(current[i]||0),amount:capital*((w[i]||0)-(current[i]||0))})),gross=trades.reduce((a,t)=>a+Math.abs(t.amount),0),fees=gross*fee/10000;
return {schema_version:'construction-browser-v1',method,holdings,cash_weight:cashw,weights_sum:total,risk,constraints:{cash_floor:cash,asset_cap:cap,sector_cap:scap},capital,trades,gross_traded_notional:gross,turnover_one_way:gross/capital/2,estimated_fees:fees,cash_after_estimated_fees:capital*cashw-fees,feasibility:capital*cashw<fees?'review_cost_cash':'feasible_before_execution',caveat:'配置及再平衡草案；不执行交易；参考碎股数量，无税、流动性和滑点模型。'}}
return {construct};})();
if(typeof module!=='undefined')module.exports=Constructor;
