/* Local, dependency-free investment engine. Also executable in Node parity tests. */
const Investment = (()=>{
const SF=['symbol','name','sector','currency','price_as_of','price','eps_ttm','revenue_growth','operating_margin','fcf_margin','debt_to_equity','period_end','filed_at','source'], PF=['date','symbol','adj_close'], NF=['price','eps_ttm','revenue_growth','operating_margin','fcf_margin','debt_to_equity'];
const PRO={balanced:[.4,.3,.3],quality:[.6,.2,.2],value:[.3,.2,.5]},RR={future_filing:'披露日期晚于研究日',future_price:'快照价格晚于研究日',stale_price:'快照价格距研究日超过120天',stale_filing:'披露距研究日超过550天',missing_metrics:'缺少必要财务字段',nonpositive_eps:'TTM每股收益不为正，PE不适用',pe_above_limit:'PE超过上限',growth_below_limit:'收入增长低于下限',debt_above_limit:'债务/权益比超过上限',negative_equity_proxy:'负债权益比为负，不适用此筛选框架',nonpositive_margin:'营业利润率或自由现金流率不为正'};
function date(s,label){if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw Error(label+': 日期须为有效YYYY-MM-DD');return Date.parse(s)}
const days=(a,b)=>(date(a,'日期')-date(b,'日期'))/86400000,clip=x=>Math.min(1,Math.max(0,x));
function number(v,label,missing=false){if(missing&&(v===''||v==null))return null;if(v===''||v==null||typeof v==='boolean'||!Number.isFinite(Number(v)))throw Error(label+': 需要有限数值，比例请写小数');return Number(v)}
function csv(text,fields,label,limit){if(typeof text!=='string'||!text.trim())throw Error(label+': 文件为空');if(new TextEncoder().encode(text).length>2000000)throw Error(label+': 超过2MB');text=text.replace(/^﻿/,'');let out=[],row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else if(quoted||cell==='')quoted=!quoted;else throw Error(label+': 引号位置错误')}else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(x=>x!==''))out.push(row);row=[];cell=''}else cell+=c}
 if(quoted)throw Error(label+': 引号未关闭');if(cell||row.length){row.push(cell.trim());out.push(row)}if(out.length<2||JSON.stringify(out[0])!==JSON.stringify(fields))throw Error(label+': 表头顺序须为 '+fields.join(','));if(out.length-1>limit)throw Error(label+': 数据行超限');return out.slice(1).map((r,i)=>{if(r.length!==fields.length)throw Error(label+'第'+(i+2)+'行列数不匹配');return Object.fromEntries(fields.map((f,j)=>[f,r[j]]))})}
const mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
function std(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function allocate(rows,method,cap,max){let selected=rows.filter(x=>x.passed).sort((a,b)=>b.score.score-a.score.score||a.symbol.localeCompare(b.symbol)).slice(0,max),raw=selected.map(x=>method==='equal'?1:method==='score_weighted'?Math.max(0,x.score.score):x.market.volatility_20d>0?1/x.market.volatility_20d:0),weights=raw.map(()=>0),free=raw.map((_,i)=>i).filter(i=>raw[i]>0),left=1;
 while(free.length){const total=free.reduce((s,i)=>s+raw[i],0),over=free.filter(i=>left*raw[i]/total>cap);if(!over.length){free.forEach(i=>weights[i]=left*raw[i]/total);break}over.forEach(i=>{weights[i]=cap;left-=cap});free=free.filter(i=>!over.includes(i))}const invested=weights.reduce((s,v)=>s+v,0);return {status:selected.length?'valid':'insufficient',method,weights_sum:invested,cash_weight:Math.max(0,1-invested),holdings:selected.map((x,i)=>({entity_id:x.symbol,sector:x.sector,weight:weights[i],raw_score:x.score.score,volatility_20d:x.market.volatility_20d,evidence_ids:x.evidence_ids})),formula_refs:['按规则分配，单票≤cap；未分配资金保留现金','score_weighted仅为启发式，不是收益预测'],constraints_applied:['long_only','hard_weight_cap']}}
function stress(p,hist){let hs=p.holdings.filter(h=>h.weight>0),sectors={};p.holdings.forEach(h=>sectors[h.sector]=(sectors[h.sector]||0)+h.weight);let base={status:'insufficient',scenarios:[],warnings:[],sector_weights:sectors,hhi:p.holdings.reduce((s,h)=>s+h.weight*h.weight,0),sector_hhi:Object.values(sectors).reduce((s,w)=>s+w*w,0),joint_return_observations:0};if(!hs.length)return base;
 const maps=hs.map(h=>new Map((hist[h.entity_id]||[]).map(r=>[r.date,r.close])));if(maps.some(m=>!m.size)){base.warnings.push('持仓缺少有效价格，风险不可计算');return base}
 const dates=[...maps[0].keys()].filter(d=>maps.every(m=>m.has(d))).sort(),R=dates.slice(1).map((d,t)=>maps.map(m=>m.get(d)/m.get(dates[t])-1)),n=R.length,w=hs.map(h=>h.weight);base.joint_return_observations=n;if(n<40){base.warnings.push('共同收益观测不足40期：'+n);return base}let gap=0;for(let i=1;i<dates.length;i++)gap=Math.max(gap,days(dates[i],dates[i-1]));if(gap>7)base.warnings.push('共同价格日期间隔超过7天，一日风险估计不可靠');
 const mu=w.map((_,j)=>mean(R.map(r=>r[j]))),cov=w.map((_,j)=>w.map((_,k)=>R.reduce((s,r)=>s+(r[j]-mu[j])*(r[k]-mu[k]),0)/(n-1))),vol=w.map((_,j)=>Math.sqrt(cov[j][j]));
 function tail(C,name){let cw=w.map((_,i)=>C[i].reduce((s,v,j)=>s+v*w[j],0)),sd=Math.sqrt(Math.max(0,w.reduce((s,v,i)=>s+v*cw[i],0))),con={};hs.forEach((h,i)=>con[h.entity_id]=sd>0?1.645*w[i]*cw[i]/sd:0);return {name,status:'valid',portfolio_loss:1.645*sd,horizon_label:'1-day',per_entity_contribution:con,assumptions:['零均值正态一日估计；共同日期样本协方差；不是校准VaR']}}
 let daily=R.map(r=>r.reduce((s,v,i)=>s+v*w[i],0)),min=Infinity,idx=0;for(let k=0;k<=n-20;k++){let wealth=1;for(let j=k;j<k+20;j++)wealth*=1+daily[j];if(wealth<min){min=wealth;idx=k}}
 let wealth=1,con=Object.fromEntries(hs.map(h=>[h.entity_id,0]));for(let t=idx;t<idx+20;t++){hs.forEach((h,j)=>con[h.entity_id]-=wealth*w[j]*R[t][j]);wealth*=1+daily[t]}
 const historical={name:'worst_20d_replay',status:'valid',portfolio_loss:1-min,horizon_label:'20-day',window_start:dates[idx],window_end:dates[idx+20],per_entity_contribution:con,assumptions:['当前权重逐期再平衡；共同日期最差20期复合回放；不是可交易回测']};return {...base,status:'valid',scenarios:[tail(cov,'parametric_95'),historical,tail(cov.map((r,i)=>r.map((_,j)=>i===j?cov[i][i]:.95*vol[i]*vol[j])),'correlation_95')]}}
function analyze(x){const asof=x.as_of||'2025-12-31';date(asof,'研究日');if(asof>new Date().toISOString().slice(0,10))throw Error('研究日不得晚于今天');let profile=x.profile||'balanced',method=x.method||'equal',cap=number(x.weight_cap??.3,'单票上限'),max=number(x.max_names??5,'持仓数'),maxpe=number(x.max_pe??35,'PE'),ming=number(x.min_growth??0,'增长'),maxd=number(x.max_debt??2,'负债权益比');if(!PRO[profile]||!['equal','score_weighted','vol_inverse'].includes(method)||cap<=0||cap>1||max<1||max>50||!Number.isInteger(max)||maxpe<=0||maxpe>200||ming< -1||ming>2||maxd<0||maxd>20)throw Error('筛选或权重参数超出允许范围');const stocks=csv(x.stocks_csv,SF,'stocks.csv',200),symbols=new Set(),currencies=new Set();stocks.forEach((r,i)=>{if(!/^[A-Z0-9][A-Z0-9.\-]{0,14}$/.test(r.symbol))throw Error('第'+(i+2)+'行symbol错误');if(symbols.has(r.symbol))throw Error('重复代码：'+r.symbol);symbols.add(r.symbol);currencies.add(r.currency);if(!/^[A-Z]{3}$/.test(r.currency))throw Error('币种须为3位大写');for(const k of ['name','sector','source'])if(!r[k]||r[k].length>500)throw Error(k+'须非空且不超过500字');for(const k of ['filed_at','period_end','price_as_of'])date(r[k],k);if(r.period_end>r.filed_at)throw Error('期末晚于披露日');NF.forEach(k=>r[k]=number(r[k],k,k!=='price'));if(r.price<=0)throw Error('price必须为正')});if(currencies.size!==1)throw Error('只支持单币种股票池');let hist=Object.fromEntries([...symbols].map(s=>[s,[]])),seen=new Set(),future=0;
 if(x.prices_csv?.trim())csv(x.prices_csv,PF,'prices.csv',80000).forEach(r=>{date(r.date,'prices date');if(!symbols.has(r.symbol))throw Error('prices包含stocks没有的代码');const key=r.symbol+'|'+r.date;if(seen.has(key))throw Error('prices重复代码/日期');seen.add(key);const v=number(r.adj_close,'adj_close');if(v<=0)throw Error('adj_close须为正');if(r.date>asof){future++;return}hist[r.symbol].push({date:r.date,close:v})});Object.values(hist).forEach(a=>a.sort((x,y)=>x.date.localeCompare(y.date)));
 let evidence=[],rows=stocks.map(r=>{let reasons=[],missing=NF.filter(k=>r[k]===null);if(r.filed_at>asof)reasons.push('future_filing');if(r.price_as_of>asof)reasons.push('future_price');if(days(asof,r.price_as_of)>120)reasons.push('stale_price');if(days(asof,r.filed_at)>550)reasons.push('stale_filing');if(missing.length)reasons.push('missing_metrics');const pe=r.eps_ttm>0?r.price/r.eps_ttm:null;if(r.eps_ttm!==null&&r.eps_ttm<=0)reasons.push('nonpositive_eps');if(pe!==null&&pe>maxpe)reasons.push('pe_above_limit');if(r.revenue_growth!==null&&r.revenue_growth<ming)reasons.push('growth_below_limit');if(r.debt_to_equity!==null&&r.debt_to_equity>maxd)reasons.push('debt_above_limit');if(r.debt_to_equity!==null&&r.debt_to_equity<0)reasons.push('negative_equity_proxy');if(['operating_margin','fcf_margin'].some(k=>r[k]!==null&&r[k]<=0))reasons.push('nonpositive_margin');let components=null;if(!missing.length&&pe!==null&&r.debt_to_equity>=0){const quality=100*(.4*clip(r.operating_margin/.3)+.4*clip(r.fcf_margin/.2)+.2*(1-clip(r.debt_to_equity/2))),growth=100*clip(r.revenue_growth/.3),value=100*clip((40-pe)/30),w=PRO[profile];components={quality,growth,value,total:w[0]*quality+w[1]*growth+w[2]*value,weights:w}}
 const bars=hist[r.symbol],v=bars.map(b=>b.close),ret=v.slice(1).map((z,i)=>z/v[i]-1);let peak=0,dd=0;v.forEach(z=>{peak=Math.max(peak,z);dd=Math.min(dd,z/peak-1)});const warnings=[];if(bars.length<41)warnings.push('不足41个价格观测，组合风险可能不可计算');if(bars.length&&days(asof,bars.at(-1).date)>7){warnings.push('历史价格末日距研究日超过7天，停止本标的压力');hist[r.symbol]=[]}
 let eid='stock-'+r.symbol;evidence.push({evidence_id:eid,source:r.source,filed_at:r.filed_at,price_as_of:r.price_as_of,inputs:r,verified:false});return {...r,entity_id:r.symbol,pe,passed:!reasons.length,exclusions:reasons,reasons:reasons.map(x=>RR[x]),missing,warnings,components,score:{score:components?.total??null},market:{volatility_20d:ret.length>=20?std(ret.slice(-20))*Math.sqrt(252):null,return_20d:v.length>20?v.at(-1)/v.at(-21)-1:null,max_drawdown:v.length>1?dd:null,observations:v.length},evidence_ids:[eid]}});
 const selected=rows.filter(r=>r.passed).sort((a,b)=>b.score.score-a.score.score||a.symbol.localeCompare(b.symbol)).map(r=>r.symbol),p=allocate(rows,method,cap,max),risk=stress(p,hist),kind=stocks.some(r=>r.source.startsWith('demo:'))?'synthetic':'user_import';let result={schema_version:'investment-browser-v0.3',as_of:asof,data_kind:kind,data_label:kind==='synthetic'?'合成示例，非真实证券':'用户提供，未独立核验',currency:[...currencies][0],screen:{rows,selected,universe_size:rows.length,excluded:rows.filter(r=>!r.passed).map(r=>({symbol:r.symbol,reasons:r.reasons})),criteria:{profile,max_pe:maxpe,min_growth:ming,max_debt:maxd}},portfolio:p,risk,evidence_ledger:evidence,parameters:{profile,max_pe:maxpe,min_growth:ming,max_debt:maxd,weight_cap:cap,max_names:max,method},warnings:['仅适用于非金融企业预筛，银行/保险/REIT需专门指标。','当前权重历史重放不是可交易回测；参数值不是盈利概率。','来源与TTM/复权口径须由用户核验。',...(future?[future+'条未来价格已排除']:[])],trace:[{step:'校验',result:rows.length+'家公司'},{step:'筛选',result:selected.length+'家通过'},{step:'配置',result:'现金'+(p.cash_weight*100).toFixed(1)+'%'},{step:'风险',result:risk.status}],content_hash:null};result.memo=memo(result);return result}
function memo(r){let a=['# FinPilot 研究备忘录',r.as_of+' / '+r.data_label+' / '+r.currency,'研究候选不是买入建议。','## 筛选条件',JSON.stringify(r.parameters),'## 候选与排除',...r.screen.rows.map(x=>x.symbol+' '+x.name+'：'+(x.passed?'通过；评分'+x.score.score.toFixed(2):x.reasons.join('；'))+'。来源 '+x.source+'，披露 '+x.filed_at),'## 配置草案',...r.portfolio.holdings.map(h=>h.entity_id+' '+(h.weight*100).toFixed(2)+'%'),'现金 '+(r.portfolio.cash_weight*100).toFixed(2)+'%','## 风险诊断',...r.risk.scenarios.map(s=>s.name+' '+s.horizon_label+'：'+(s.portfolio_loss===null?'不可计算':(s.portfolio_loss*100).toFixed(3)+'%')+(s.window_start?'；窗口 '+s.window_start+' 至 '+s.window_end:'')),'正数表示损失，负数表示收益。历史重放不是可交易回测。','## 人工复核',...r.warnings,...r.risk.warnings];return a.join('\n\n')+'\n'}
return {analyze,csv,memo,SF,PF};})();
if(typeof module!=='undefined')module.exports=Investment;
